# Generated by Django 5.2.4 on 2026-03-01 05:22

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, null=True, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("CNY", "Chinese Yuan"),
                    ("KRW", "South Korean Won"),
                    ("RUB", "Russian Ruble"),
                    ("KZT", "Kazakhstani Tenge"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("SEK", "Swedish Krona"),
                    ("BRL", "Brazilian Real"),
                    ("INR", "Indian Rupee"),
                    ("SGD", "Singapore Dollar"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
