# Generated by Django 5.2.4 on 2026-03-03 11:46

import apps.common.enums
import apps.tournaments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0003_alter_race_slug_alter_series_slug"),
        ("tournaments", "0002_tournament_slug_alter_tournament_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="prize_pool",
            new_name="prize_fund",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="location",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="organizer",
        ),
        migrations.AddField(
            model_name="tournament",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.tournaments.models.logo_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="regulations_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="series",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="races.series",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "upcoming"),
                    ("live", "live"),
                    ("finished", "finished"),
                    ("cancelled", "cancelled"),
                ],
                default=apps.common.enums.RaceStatusEnum["FINISHED"],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="total_rounds",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="year",
            field=models.PositiveSmallIntegerField(default=2026),
            preserve_default=False,
        ),
    ]
