# Generated by Django 5.2.4 on 2026-03-04 11:14

from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.contrib.contenttypes.management import create_contenttypes
from django.db import migrations


def create_content_manager_group(apps, schema_editor):
    app_config = global_apps.get_app_config("tournaments")

    create_contenttypes(app_config, verbosity=0)
    create_permissions(app_config, verbosity=0)

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    group, _ = Group.objects.get_or_create(name="ContentManager")

    permissions = Permission.objects.filter(
        codename__in=["add_tournament", "change_tournament", "delete_tournament"]
    )
    group.permissions.set(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_driverstanding"),
    ]

    operations = [
        migrations.RunPython(create_content_manager_group),
    ]
