# Generated by Django 5.2.4 on 2026-03-06 15:08

import apps.tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_auto_20260304_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tournaments.models.logo_upload_path, validators=[apps.tournaments.models.validate_image_size]),
        ),
    ]
