# Generated by Django 5.0.4 on 2026-02-24 13:29

import autoslug.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, null=True, populate_from="name", unique=True
            ),
        ),
    ]
