# Generated by Django 5.0.4 on 2026-02-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_tag_slug"),
        ("news", "0002_create_author_group"),
    ]

    operations = []
