# Generated by Django 5.2.4 on 2026-03-01 05:31

import apps.news.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_merge_0002_alter_tag_slug_0002_create_author_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(200),
                    django.core.validators.MaxLengthValidator(7500),
                ],
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.news.models.article_cover_path,
                validators=[apps.news.models.validate_image_size],
                verbose_name="Cover Image",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
