# Generated by Django 5.0.4 on 2026-02-23 13:32

import autoslug.fields

from django.db import migrations, models

import apps.races.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cat", "cat"),
                            ("moto", "moto"),
                            ("endurance", "endurance"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.races.models.logo_upload_path,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
