# Generated by Django 5.0.4 on 2026-02-23 14:30

import autoslug.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="series",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="category",
            field=models.CharField(
                choices=[("car", "car"), ("moto", "moto"), ("endurance", "endurance")],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="races.series"
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "upcoming"),
                            ("live", "live"),
                            ("finished", "finished"),
                            ("cancelled", "cancelled"),
                        ],
                        max_length=10,
                    ),
                ),
                ("watch_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "watch_platform",
                    models.CharField(
                        choices=[
                            ("f1_tv", "f1_tv"),
                            ("youtube", "youtube"),
                            ("twitch", "twitch"),
                            ("dazn", "dazn"),
                            ("espn", "espn"),
                            ("sky_sports", "sky_sports"),
                        ],
                        max_length=20,
                    ),
                ),
                ("laps_total", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
