# Generated by Django 5.2.4 on 2026-03-06 15:08

import autoslug.fields
import django.db.models.deletion
import django_countries.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_alter_driver_options_driver_bio_driver_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('length_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lap_record', models.DurationField(blank=True, null=True)),
                ('number_of_turns', models.PositiveIntegerField(default=0)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='tracks/maps/')),
                ('lap_record_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_record', to='drivers.driver')),
            ],
            options={
                'ordering': ['name', 'country'],
            },
        ),
    ]
