# Generated by Django 5.2.4 on 2026-05-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("race_tracks", "0001_initial"),
    ]

    operations = []
