# Generated by Django 5.2.4 on 2026-03-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firestore_avatar_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="use_firestore_avatar",
            field=models.BooleanField(default=False),
        ),
    ]
