# Generated by Django 6.0.2 on 2026-02-28 19:43

import autoslug.fields
import django_countries.fields

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.drivers.models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        ("races", "0003_alter_race_slug_alter_series_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "Driver", "verbose_name_plural": "Drivers"},
        ),
        migrations.AddField(
            model_name="driver",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="driver",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driver",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AddField(
            model_name="driver",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="driver",
            name="last_name",
            field=models.CharField(
                default="default-last-name", max_length=100, verbose_name="Last Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driver",
            name="nationality",
            field=django_countries.fields.CountryField(
                default="en", max_length=2, verbose_name="Nationality"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driver",
            name="number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Racing Number"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.drivers.models.profile_image_upload_path,
                verbose_name="Profile Image",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="default-slug",
                editable=False,
                populate_from=apps.drivers.models.driver_slug,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="driver",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="First Name"),
        ),
        migrations.CreateModel(
            name="DriverResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Finish Position"
                    ),
                ),
                (
                    "grid_position",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Grid Position"
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Points"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("finished", "finished"),
                            ("dnf", "dnf"),
                            ("dns", "dns"),
                            ("dsq", "dsq"),
                        ],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "fastest_lap",
                    models.BooleanField(default=False, verbose_name="Fastest Lap"),
                ),
                (
                    "laps_completed",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Laps Completed"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="drivers.driver",
                        verbose_name="Driver",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="driver_results",
                        to="races.race",
                        verbose_name="Race",
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver Result",
                "verbose_name_plural": "Driver Results",
                "unique_together": {("driver", "race")},
            },
        ),
    ]
