# Generated by Django 5.0.4 on 2026-02-24 13:29

import autoslug.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0002_team_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamStuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        null=True,
                        populate_from="name",
                        unique=True,
                    ),
                ),
                ("fist_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("in_team_sincAe", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Team Stuff",
                "verbose_name_plural": "Team Stuffs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster",
                        to="teams.team",
                    ),
                ),
                (
                    "stuff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="team_stuff.teamstuff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Roster",
                "verbose_name_plural": "Team Rosters",
                "ordering": ["start_date"],
                "unique_together": {("team", "stuff", "start_date")},
            },
        ),
    ]
