# Generated by Django 5.2.4 on 2026-03-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("team_stuff", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamroster",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roster",
                to="teams.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamroster",
            unique_together={("team", "staff_member", "start_date")},
        ),
    ]
