# Generated by Django 5.0.4 on 2026-02-22 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(max_length=3)),
                ("logo", models.ImageField(upload_to="team_logo")),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "founded_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("description", models.TextField(blank=True)),
                ("budget", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "budget_currency",
                    models.CharField(blank=True, default="USD", max_length=3),
                ),
                ("main_sponsor", models.CharField(blank=True, max_length=255)),
                ("secondary_sponsor", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["short_name"], name="teams_team_short_n_eadde9_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamStandings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "position",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                ("wins", models.PositiveIntegerField(default=0)),
                ("podiums", models.PositiveIntegerField(default=0)),
                ("def_count", models.PositiveIntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Standing",
                "verbose_name_plural": "Team Standings",
                "ordering": ["position"],
                "unique_together": {("team", "tournament")},
            },
        ),
    ]
