# Generated by Django 5.2.4 on 2026-03-13 09:56

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="team",
            new_name="teams_team_short_n_eadde9_idx",
            old_name="teams_team_short_n_8f8c2f_idx",
        ),
        migrations.AddField(
            model_name="team",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="teams/banners/"),
        ),
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, null=True, populate_from="name", unique=True
            ),
        ),
    ]
