# Generated by Django 5.0.4 on 2026-02-24 13:29

import autoslug.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, null=True, populate_from="name", unique=True
            ),
        ),
    ]
