# Generated by Django 5.0.4 on 2026-02-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
